Feature/7 add accident list
rjhdby/android_motoDTP_v2 pull request #15
Opened 2021-04-22 10:23 UTC by Trunker2010

2021-04-22 11:32 UTC, elagin requested changes
Все исправить и приложить скриншот работающего окна.
Кстати, не вижу изменений в моках.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/data/network/accident/AccidentResponse.kt
> +//        var hardness: AccidentHardness,
Был готовый класс AccidentHardness. По какой причине он не используется?

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +//    var hardness: AccidentHardness,
Опять исключен AccidentHardness

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Hardness.kt
> +enum class Hardness constructor(val text: String) {
Чем не устраивал AccidentHardness ?

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Лишняя пустая строка.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Пустая строка.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Пустые строки.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/root/RootActivity.kt
> +
Достаточно одной.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/root/RootViewModel.kt
> +
Одной было мало?

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/ui/rows/accident/CommonRow.kt
> +        left = 4
Вынести в константы класса.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/ui/rows/accident/OwnedActiveRow.kt
> +
Пустая строка.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/ui/rows/accident/OwnedRow.kt
> +        left = 16
В константы класса.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/ui/rows/accident/Row.kt
> +//todo refactor
Не понятное описание. Что именно надо рефачить?

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/ui/rows/accident/Row.kt
> +
Пустая строка.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/AccidentEpoxyController.kt
> +    fun setAccidents(accident: MutableList<Accident>) {
setAccidents Ни где не вызывается.

2021-04-22 11:32 UTC, elagin commented on app/src/main/res/layout/fragment_home.xml
> +<!--TODO TextView перекрывает все что под ним-->
Не понятный комметарий.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/ui/rows/accident/Row.kt
> +            minLines = 3
Вынести в константы

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/domain/utils/DateUtils.kt
> +@file:JvmName("DateUtils")
Убрать.

2021-04-22 11:32 UTC, elagin commented on app/src/main/java/motocitizen/data/utils/LocationUtils.kt
> +@file:JvmName("LocationUtils")
Убрать.

2021-04-24 17:46 UTC, Trunker2010 commented on app/src/main/java/motocitizen/data/network/accident/AccidentResponse.kt
> +//        var hardness: AccidentHardness,
отсутствует нужное поле "text"

2021-04-26 12:11 UTC, elagin commented on app/src/main/java/motocitizen/data/network/accident/AccidentResponse.kt
> +//        var hardness: AccidentHardness,
Ответ не понятный.

2021-04-26 12:15 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +//    var hardness: AccidentHardness,
AccidentType тоже есть, зачем дубликат Type?

2021-04-26 12:50 UTC, elagin requested changes

2021-04-26 12:50 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +    @Inject
XXXUseCase подключаются во ViewModel

2021-04-26 12:50 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +    lateinit var trustManager: TrustManager
Подозреваю, что это так же во ViewModel надо использовать.

2021-04-26 12:50 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Ты вообще не просматриваешь что коммитишь? Зачем опять пустая строка?

2021-04-26 12:50 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +                override fun onSubscribe(d: Disposable) {
Зачем тут нужен пустой onSubscribe ?

2021-04-26 12:50 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +    fun getAccidentsList() {
Пустая функция

2021-04-27 12:22 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +            String.format("<b>%s</b>", accident.messages)
Вынести в константу.

2021-04-27 12:23 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        return String.format(
В константу.

2021-04-27 12:23 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        val sdf = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZZ", Locale.getDefault())
В константу.

2021-04-27 12:24 UTC, elagin commented on app/src/main/java/motocitizen/domain/utils/DateUtils.kt
> +    return String.format("%dч %dм", minutes / 60, minutes % 60)
Контанта.

2021-04-27 12:27 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +        DaggerApp_HiltComponents_SingletonC.builder()
По смотри как это сделано в других местах.

2021-04-27 12:28 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +        getAccidentUseCase.getAccidentList("1", 999)
Временный код, должно быть //todo

2021-04-27 12:29 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +
Лишняя пустая строка.

2021-04-27 12:43 UTC, elagin requested changes
Осталось еще чуть чуть.

2021-04-27 16:17 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +//    var hardness: AccidentHardness,
Исправлено, используется AccidentType

2021-04-27 16:17 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Hardness.kt
> +enum class Hardness constructor(val text: String) {
исправлено

2021-04-27 16:17 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
исправлено

2021-04-27 16:18 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
исправлено

2021-04-27 16:20 UTC, Trunker2010 commented on app/src/main/res/layout/fragment_home.xml
> +<!--TODO TextView перекрывает все что под ним-->
Исправлено

2021-04-27 16:20 UTC, Trunker2010 commented on app/src/main/java/motocitizen/ui/rows/accident/Row.kt
> +            minLines = 3
Вынес

2021-04-27 16:21 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/utils/DateUtils.kt
> +@file:JvmName("DateUtils")
Убрал

2021-04-27 16:21 UTC, Trunker2010 commented on app/src/main/java/motocitizen/data/utils/LocationUtils.kt
> +@file:JvmName("LocationUtils")
Убрал

2021-04-27 16:21 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +    @Inject
Исправлено

2021-04-27 16:22 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +    lateinit var trustManager: TrustManager
Разобрался, исправил

2021-04-27 16:22 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Исправил

2021-04-27 16:22 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +                override fun onSubscribe(d: Disposable) {
Исправил

2021-04-27 16:23 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +    fun getAccidentsList() {
Исправил

2021-04-27 16:24 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +            String.format("<b>%s</b>", accident.messages)
Вынес

2021-04-27 16:27 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        return String.format(
не совсем понял, что нужно выносить? ", " и ""?

2021-04-27 16:28 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        val sdf = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZZ", Locale.getDefault())
вынес

2021-04-27 16:28 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/utils/DateUtils.kt
> +    return String.format("%dч %dм", minutes / 60, minutes % 60)
числа тоже?

2021-04-27 16:29 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +        DaggerApp_HiltComponents_SingletonC.builder()
Разобрался, исправил

2021-04-27 16:30 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +        getAccidentUseCase.getAccidentList("1", 999)
добавил

2021-04-27 16:31 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +
Убрал

2021-04-27 18:54 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Исправлено

2021-04-27 18:55 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/root/RootActivity.kt
> +
Исправлено

2021-04-27 18:56 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/root/RootViewModel.kt
> +
Исправлено

2021-04-27 18:58 UTC, Trunker2010 commented on app/src/main/java/motocitizen/ui/rows/accident/CommonRow.kt
> +        left = 4
Вынес

2021-04-27 18:59 UTC, Trunker2010 commented on app/src/main/java/motocitizen/ui/rows/accident/OwnedActiveRow.kt
> +
Убрал

2021-04-27 19:00 UTC, Trunker2010 commented on app/src/main/java/motocitizen/ui/rows/accident/OwnedRow.kt
> +        left = 16
Вынес

2021-04-27 19:00 UTC, Trunker2010 commented on app/src/main/java/motocitizen/ui/rows/accident/Row.kt
> +//todo refactor
Перенес из старого проекта, там было так, исправил.

2021-04-27 19:02 UTC, Trunker2010 commented on app/src/main/java/motocitizen/ui/rows/accident/Row.kt
> +
убрал

2021-04-28 11:05 UTC, elagin requested changes

2021-04-28 11:05 UTC, elagin commented on app/src/main/java/motocitizen/data/network/accident/AccidentResponse.kt
> +//    var updated: String,
Убрать лишний мусор AccidentType и AccidentHardness уже указаны выше.

2021-04-28 11:05 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +//        @field:JsonSerialize(using = ToStringSerializer::class) val creator: ObjectId,
Это точно здесь нужно?

2021-04-28 11:05 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +    //TODO реализовать логику
Какую логику?

2021-04-28 11:05 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        return String.format(
Пусть пока останется, все равно потом переделывать надо.

2021-04-28 11:10 UTC, elagin requested changes

2021-04-28 11:10 UTC, elagin commented on app/src/main/java/motocitizen/domain/utils/DateUtils.kt
> +    return String.format("%dч %dм", minutes / 60, minutes % 60)
Конечно.

2021-04-28 11:13 UTC, rjhdby commented on app/src/main/java/motocitizen/data/network/accident/AccidentResponse.kt
> +//    var updated: String,
А там не джексон? По идее ему не нужны анноташки, если поля по именам совпадают.

2021-04-28 11:15 UTC, rjhdby commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        )
Тут лучше предопределённый EnumSet. Поиск по массиву это O(n), по EnumSet это O(1)

2021-04-28 11:20 UTC, rjhdby commented on app/src/main/java/motocitizen/ui/rows/accident/OwnedEndedRow.kt
> +}
Наверное геттеры не особо тут нужны. Лучше напрямую присвоить

2021-04-28 11:22 UTC, rjhdby commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
>      val created: String,// Идентификатор аварии
Хороший пример плохого комментария :)

2021-04-28 11:22 UTC, rjhdby commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
>      val created: String,// Идентификатор аварии
Хороший пример плохого комментария :)

2021-04-28 11:33 UTC, rjhdby commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        )
Тут лучше предопределённый EnumSet. Поиск по массиву это O(n), по EnumSet это O(1)

2021-04-28 12:39 UTC, Trunker2010 commented on app/src/main/java/motocitizen/data/network/accident/AccidentResponse.kt
> +//    var updated: String,
gson, работает без SerializedName, убрал

2021-04-28 12:43 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +//        @field:JsonSerialize(using = ToStringSerializer::class) val creator: ObjectId,
не разобрался в назначении этой строки (так было в старом проекте), убрал.

2021-04-28 12:50 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +    //TODO реализовать логику
исправил

2021-04-28 13:00 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
>      val created: String,// Идентификатор аварии
Исправил

2021-04-28 13:04 UTC, Trunker2010 commented on app/src/main/java/motocitizen/ui/rows/accident/OwnedEndedRow.kt
> +}
исправил

2021-04-28 15:04 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        )
сделал

2021-04-28 15:22 UTC, elagin approved these changes

2021-04-28 19:49 UTC, merged