Feature/6 add map
rjhdby/android_motoDTP_v2 pull request #19
Opened 2021-05-05 15:01 UTC by Trunker2010

2021-05-05 22:22 UTC, elagin requested changes

2021-05-05 22:22 UTC, elagin commented on app/src/main/java/motocitizen/app/utils/MapUtils.kt
> +        age < 6 -> SEMI_DENSE
Константы.

2021-05-05 22:22 UTC, elagin commented on app/src/main/java/motocitizen/data/utils/LocationUtils.kt
> +    (distanceTo(LocListener.currentLocation.value!!) * 1000).toLong()
Константа.

2021-05-05 22:22 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +
Пустая строка.

2021-05-05 22:22 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/map/MapViewModel.kt
> +    private fun loadAccidentLost() {
loadAccidentL**I**st?

2021-05-05 22:22 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/root/RootViewModel.kt
> +        locationManager.requestLocationUpdates(provider!!, 100L, 1f, locationListener)
Нужна константа.

2021-05-05 22:22 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        sdf = SimpleDateFormat(DATE_TIME_PATTERN, Locale.getDefault())
Зачем sdf инициализируется в двух местах одним и тем же?

2021-05-05 22:22 UTC, elagin commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        return sdf.parse(created).time
Требуется sdf.parse(created)!!

2021-05-06 11:34 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/root/RootViewModel.kt
> +        locationManager.requestLocationUpdates(provider!!, 100L, 1f, locationListener)
Тут лучше переделывать на FusedLocationProviderClient, так будет лучше. Пока поставлю как было, 1000, исправил

2021-05-06 11:40 UTC, Trunker2010 commented on app/src/main/java/motocitizen/app/utils/MapUtils.kt
> +        age < 6 -> SEMI_DENSE
Исправил

2021-05-06 11:49 UTC, Trunker2010 commented on app/src/main/java/motocitizen/data/utils/LocationUtils.kt
> +    (distanceTo(LocListener.currentLocation.value!!) * 1000).toLong()
Исправил

2021-05-06 11:50 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +
Исправил

2021-05-06 11:51 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/map/MapViewModel.kt
> +    private fun loadAccidentLost() {
Исправил

2021-05-06 12:01 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        sdf = SimpleDateFormat(DATE_TIME_PATTERN, Locale.getDefault())
Исправил

2021-05-06 12:01 UTC, Trunker2010 commented on app/src/main/java/motocitizen/domain/model/accident/Accident.kt
> +        return sdf.parse(created).time
Исправил

2021-05-09 19:47 UTC, merged