Добавлена авторизация через Вконтакте
rjhdby/android_motoDTP_v2 pull request #61
Opened 2021-05-18 15:18 UTC by Trunker2010

2021-05-18 19:03 UTC, elagin requested changes

2021-05-18 19:03 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/AuthVkFragment.kt
> +        "https://oauth.vk.com/authorize?client_id=6355438&display=mobile&redirect_uri=http://188.166.126.84:8080/v1/user/register/vk&response_type=code&v=5.130"
Во первых константа, во вторых url бэка надо брать из текущей конфигурации: BuildConfig.SERVER_URL

2021-05-18 19:03 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/AuthVkFragment.kt
> +                jsInterface, "HTMLOUT"
Константа.

2021-05-18 19:03 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/VkAuthWebViewClient.kt
> +    private val AUTH_TOKEN_PREFIX = "http://188.166.126.84:8080/v1/user/register/vk?code="
Так же из текущей конфигурации.

2021-05-18 19:03 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/VkAuthWebViewClient.kt
> +                loadUrl("javascript:window.HTMLOUT.processHTML('<head>'+document.getElementsByTagName('html')[0].innerHTML+'</head>');")
Константа.

2021-05-18 19:03 UTC, elagin commented on app/src/main/java/motocitizen/data/network/factory/HttpClientFactory.kt
>                  //todo подставлять реальный токен
todo больше не нужно.

2021-05-18 19:03 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/root/RootViewModel.kt
> +    fun checkToken(): Boolean {
Эта функция не нужна, вполне можно обойтись getToken().

2021-05-19 06:52 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/AuthVkFragment.kt
> +        "https://oauth.vk.com/authorize?client_id=6355438&display=mobile&redirect_uri=http://188.166.126.84:8080/v1/user/register/vk&response_type=code&v=5.130"
Исправил

2021-05-19 06:54 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/AuthVkFragment.kt
> +                jsInterface, "HTMLOUT"
Исправил

2021-05-19 07:08 UTC, elagin requested changes

2021-05-19 07:08 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/AuthVkViewModel.kt
> +    private val sharedPrefsStorageImpl: SharedPrefsStorageImpl
Нужно использовать через репы. Пример class LoginDataRepo.

2021-05-19 07:13 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/VkAuthWebViewClient.kt
> +    private val AUTH_TOKEN_PREFIX = "http://188.166.126.84:8080/v1/user/register/vk?code="
Исправил

2021-05-19 07:16 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/VkAuthWebViewClient.kt
> +                loadUrl("javascript:window.HTMLOUT.processHTML('<head>'+document.getElementsByTagName('html')[0].innerHTML+'</head>');")
Исправил

2021-05-19 07:17 UTC, Trunker2010 commented on app/src/main/java/motocitizen/data/network/factory/HttpClientFactory.kt
>                  //todo подставлять реальный токен
Исправил

2021-05-19 07:19 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/root/RootViewModel.kt
> +    fun checkToken(): Boolean {
Исправил

2021-05-19 08:02 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/AuthVkViewModel.kt
> +    private val sharedPrefsStorageImpl: SharedPrefsStorageImpl
Исправил

2021-05-19 08:33 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/AuthVkFragment.kt
> +        "https://oauth.vk.com/authorize?client_id=6355438&display=mobile&redirect_uri=http://188.166.126.84:8080/v1/user/register/vk&response_type=code&v=5.130"
Не так, см. ниже.

2021-05-19 08:35 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/AuthVkFragment.kt
> +                jsInterface, "HTMLOUT"
Нужно делать "над классом". Ты же правильно делал в других местах. Посмотри примеры кода.
```
private const val VK_AUTH_URL = "......"
private const val JS_INTERFACE_NAME = "HTMLOUT"

@AndroidEntryPoint
class AuthVkFragment...
```

2021-05-19 08:36 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/VkAuthWebViewClient.kt
> +    private val AUTH_TOKEN_PREFIX = "http://188.166.126.84:8080/v1/user/register/vk?code="
Тоже вынести из класса.

2021-05-19 08:37 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/auth/vk/VkAuthWebViewClient.kt
> +                loadUrl("javascript:window.HTMLOUT.processHTML('<head>'+document.getElementsByTagName('html')[0].innerHTML+'</head>');")
Закрою, см. выше.

2021-05-19 08:40 UTC, elagin requested changes
Кроме констант все хорошо.

2021-05-19 09:02 UTC, elagin approved these changes

2021-05-19 09:02 UTC, merged