Добавлена локация в запрос списка инцидентов
rjhdby/android_motoDTP_v2 pull request #71
Opened 2021-05-19 17:29 UTC by Trunker2010

2021-05-19 20:38 UTC, elagin requested changes

2021-05-19 20:38 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Пустая строка.

2021-05-19 20:38 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
>              //todo Подставить реальные данные
Подозреваю, что это todo больше не нужно.

2021-05-19 20:38 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/root/RootActivity.kt
> +            Timber.d(e)
Нельзя смешивать уровни логирования. 
catch (e: Exception)
должен быть Timber.**e**(e)

2021-05-19 20:38 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +                lastLocation.value = latLng
Зачем нам lastKnownLocation и  lastLocation ? Получается странная логика. Мы хотим загрузить список инцидентов. Для этого делаем:
        rootActivity.updateLastLocation {
            viewModel.loadAccidentList(
                it!!.latitude,
                it.longitude
            )
Т.е. определяем координаты и дергаем бэк. Затем мы получаем ответ и в
 lastLocation.observe(this) {}
ждем изменений lastLocation который мы только что изменили? 
На момент отправки запроса мы уже знаем наши координаты и спокойно можем нарисовать список с замерами расстояний до каждого инцидента.

2021-05-20 07:45 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Исправил

2021-05-20 07:46 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
>              //todo Подставить реальные данные
Убрал

2021-05-20 07:47 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/root/RootActivity.kt
> +            Timber.d(e)
Исправил

2021-05-20 15:24 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +                lastLocation.value = latLng
Исправил

2021-05-20 16:06 UTC, elagin requested changes

2021-05-20 16:06 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +        if ((requireActivity() as RootActivity).checkGpsEnable() && App.isLocPermission) {
Получили данные с бэка, выяснили, что геолокация выключена и что, просто не показали данные юзеру? Все ругалки должны быть до запроса на бэк, чтобы его понапрасну не дергать. Да и с момента запроса до этого места обычно мало времени проходит. Таймаут на 30 сек. стоит, даже если бэк заснул.

2021-05-20 16:06 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +        loadAccidents()
Зря переименовал, слово list лучше показывает что речь идет о списке, чем буква s.

2021-05-20 16:06 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Совсем код не проверяешь перед коммитами?

2021-05-20 16:24 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +        if ((requireActivity() as RootActivity).checkGpsEnable() && App.isLocPermission) {
Исправил

2021-05-20 16:25 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +        loadAccidents()
Исправил

2021-05-20 16:28 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeFragment.kt
> +
Исправил

2021-05-20 17:13 UTC, elagin approved these changes

2021-05-20 17:13 UTC, merged