Добавлен экран настроек, передача radius и depth в запрос списка инцидентов
rjhdby/android_motoDTP_v2 pull request #79
Opened 2021-05-28 16:28 UTC by Trunker2010

2021-05-29 21:16 UTC, elagin requested changes
1) Нужно чтобы оба поля были больше 0.

2) Падает при запуске:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: motocitizen.main, PID: 21943
    java.lang.NullPointerException
        at motocitizen.data.repos.SettingsDataRepo.getDeep(SettingsDataRepo.kt:16)
        at motocitizen.presentation.screens.home.HomeViewModel.loadAccidentList(HomeViewModel.kt:26)
        at motocitizen.presentation.screens.home.HomeFragment$loadAccidentList$1.invoke(HomeFragment.kt:73)
        at motocitizen.presentation.screens.home.HomeFragment$loadAccidentList$1.invoke(HomeFragment.kt:21)
        at motocitizen.presentation.screens.root.RootActivity$updateLastLocation$1$1.onSuccess(RootActivity.kt:94)
        at motocitizen.presentation.screens.root.RootActivity$updateLastLocation$1$1.onSuccess(RootActivity.kt:44)
        at com.google.android.gms.tasks.zzn.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
```

2021-05-29 21:16 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +                depth = deep
Так depth  или deep ?

2021-05-29 21:16 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/root/RootActivity.kt
> +        setSupportActionBar(root_toolbar)
Зачем отдельная функция для вызова одной функции, которая все равно вызывается из одного места?
Перенести setSupportActionBar(root_toolbar) в initViews()

2021-05-29 21:16 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/settings/root/SettingsActivity.kt
> +        val navHostFragment =
Нам нужна навигация, если мы ни куда не переходим?

2021-05-29 21:16 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +//            TODO Реадизовать выход из сессии
Эта задача уже готова, лучше сразу сделать на её ссылку:
//todo #67 Реализовать возможность выхода из сессии

2021-05-29 21:16 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +                    if (it != null && it.isNotEmpty()) {
Фигурные скобки тут лишние.

2021-05-29 21:16 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +                                .toInt() > MAX_DEEP_HORS && (App.user.role == UserRole.USER || App.user.role == UserRole.READ_ONLY)
Причем тут роли?

2021-05-29 21:16 UTC, elagin commented on app/src/main/res/values/strings.xml
> +    <string name="settings">Натройки</string>
Очепятка.

2021-05-29 21:16 UTC, elagin commented on app/src/main/res/values/strings.xml
> +    <string name="settings_deep_key">hours.ago</string>
deep или ago... Зачем по-разному называть одно и то же?

2021-05-29 21:16 UTC, elagin commented on app/src/main/java/motocitizen/app/App.kt
> +        lateinit var user: User
Зачем нам тут User? Его легко можно добыть в GetUserUseCase.

2021-05-29 21:16 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +        val deep = settingsDataRepo.getDeep().toInt()
Отправлять на бэк будем часто, а заглядывать в настройки редко. Значит хранить надо в Int.

2021-05-29 21:16 UTC, elagin commented on app/src/main/res/values/strings.xml
> +    <string name="H">" ч."</string>
`H` - Один символ - очень короткое название для строки.

2021-05-31 07:37 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/home/HomeViewModel.kt
> +                depth = deep
Исправил, deepth

2021-05-31 07:40 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/root/RootActivity.kt
> +        setSupportActionBar(root_toolbar)
Исправил

2021-05-31 07:57 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/settings/root/SettingsActivity.kt
> +        val navHostFragment =
Я бы пока оставил

2021-05-31 08:01 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +//            TODO Реадизовать выход из сессии
Исправил

2021-05-31 08:04 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +                    if (it != null && it.isNotEmpty()) {
Исправил

2021-05-31 08:12 UTC, Trunker2010 commented on app/src/main/res/values/strings.xml
> +    <string name="settings">Натройки</string>
Исправил

2021-05-31 08:44 UTC, Trunker2010 commented on app/src/main/res/values/strings.xml
> +    <string name="settings_deep_key">hours.ago</string>
исправил

2021-05-31 08:48 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +                                .toInt() > MAX_DEEP_HORS && (App.user.role == UserRole.USER || App.user.role == UserRole.READ_ONLY)
Исправил

2021-05-31 16:37 UTC, Trunker2010 commented on app/src/main/java/motocitizen/app/App.kt
> +        lateinit var user: User
Исправил

2021-06-01 20:47 UTC, elagin requested changes

2021-06-01 20:47 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +//const val DEEP_MAX_HORS = 24
Комент без todo оно точно нужно?

2021-06-01 20:47 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +const val DEEP_MIN = 1
depth?

2021-06-01 20:47 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +    private fun innitDeepPreference() {
initDepthPreference()?

2021-06-01 20:47 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +        updateDeepSummary()
Сделай поиск по всему проекту "deep"

2021-06-01 20:47 UTC, elagin commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsViewModel.kt
> +    fun getUser(): User? {
Кажется ни где не используется.

2021-06-02 13:12 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsViewModel.kt
> +    fun getUser(): User? {
Убрал

2021-06-02 13:13 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +//const val DEEP_MAX_HORS = 24
Убрал

2021-06-02 13:15 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +const val DEEP_MIN = 1
depth

2021-06-02 13:17 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +    private fun innitDeepPreference() {
Исправил

2021-06-02 13:22 UTC, Trunker2010 commented on app/src/main/java/motocitizen/presentation/screens/settings/settings/SettingsFragment.kt
> +        updateDeepSummary()
Сделано

2021-06-02 13:53 UTC, elagin approved these changes

2021-06-02 13:53 UTC, merged